name: "Refresh branch to match target branch"
description: "Refresh the current branch to match the target branch, typically used to keep feature branches up to date."
author: "reality-collective"
inputs:
  target-branch:
    description: "The branch to refresh the current branch against."
    required: true
  source-branch:
    description: "The source branch to refresh from."
    required: true

runs:
  using: "composite"
  steps:
    - name: Script Version
      run: |
        echo "::group::Script Versioning"
        $scriptVersion = "1.0.0"
        echo "Build Script Version: $scriptVersion"
        echo "::endgroup::"
      shell: pwsh
    - uses: actions/checkout@v5
      with:
        ref: ${{ inputs.target-branch }}
        clean: true
        token: ${{ secrets.GIT_PAT }}
    - name: Refresh from Source Branch
      run: |
        git pull origin ${{ inputs.source-branch }}
        git commit -m "Branch ${{ inputs.target-branch }} updated with changes from ${{ inputs.source-branch }} [skip ci]"
        git push origin ${{ inputs.target-branch }}
        echo "Branch ${{ inputs.target-branch }} updated with changes from ${{ inputs.source-branch }}"
      shell: pwsh
